package org.culpan.webhero.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

/**
 * Created by USUCUHA on 7/14/2016.
 */
@DynamoDBTable(tableName = "heroes")
public class Hero {
    private String id;

    private String name;

    private Integer speed;

    private Integer dex;

    private Integer con;

    private Integer recovery;

    private Integer stun;

    private Integer body;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "speedIndex")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "speedIndex")
    public Integer getSpeed() {
        return speed;
    }

    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    @DynamoDBAttribute
    public Integer getDex() {
        return dex;
    }

    public void setDex(Integer dex) {
        this.dex = dex;
    }

    @DynamoDBAttribute
    public Integer getCon() {
        return con;
    }

    public void setCon(Integer con) {
        this.con = con;
    }

    @DynamoDBAttribute
    public Integer getRecovery() {
        return recovery;
    }

    public void setRecovery(Integer recovery) {
        this.recovery = recovery;
    }

    @DynamoDBAttribute
    public Integer getStun() {
        return stun;
    }

    public void setStun(Integer stun) {
        this.stun = stun;
    }

    @DynamoDBAttribute
    public Integer getBody() {
        return body;
    }

    public void setBody(Integer body) {
        this.body = body;
    }
}
